joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
  right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']
  publish_rate: 10
  pose_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
  twist_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
  wheel_separation: 0.4
  wheel_radius: 0.08
  cmd_vel_timeout: 0.25
  odom_frame_id: odom
  base_frame_id: base_footprint
  enable_odom_tf: true

ackermann_steering_controller:
  type: "ackermann_steering_controller/AckermannSteeringController"
  front_steer: ['front_left_steering_joint', 'front_right_steering_joint']
  rear_wheel: ['rear_left_wheel_joint', 'rear_right_wheel_joint']
  wheelbase: 0.5          # 前后轴距（单位：米）
  track: 0.4              # 前轮轮距（单位：米）
  cmd_timeout: 0.5
  odom_frame_id: odom
  base_frame_id: base_footprint
  publish_rate: 10
  pose_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
  twist_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]

velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - front_left_wheel_joint
    - front_right_wheel_joint
    - rear_left_wheel_joint
    - rear_right_wheel_joint

# 前轮转向控制器（ackermann_front用）
front_left_steering_controller:
  type: position_controllers/JointPositionController
  joint: front_left_steering_joint

front_right_steering_controller:
  type: position_controllers/JointPositionController
  joint: front_right_steering_joint

# 后轮转向控制器（ackermann_rear用）
rear_left_steering_controller:
  type: position_controllers/JointPositionController
  joint: rear_left_steering_joint

rear_right_steering_controller:
  type: position_controllers/JointPositionController
  joint: rear_right_steering_joint

gazebo_ros_control:
  pid_gains:
    front_left_wheel_joint: {p: 1.0, i: 0.05, d: 0.0}
    front_right_wheel_joint: {p: 1.0, i: 0.05, d: 0.0}
    rear_left_wheel_joint: {p: 1.0, i: 0.05, d: 0.0}
    rear_right_wheel_joint: {p: 1.0, i: 0.05, d: 0.0}
    front_left_steering_joint: {p: 1000, i: 0.0, d: 1.0}
    front_right_steering_joint: {p: 1000, i: 0.0, d: 1.0}
    rear_left_steering_joint: {p: 1000, i: 0.0, d: 1.0}
    rear_right_steering_joint: {p: 1000, i: 0.0, d: 1.0}