diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
  right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']
  publish_rate: 10
  pose_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
  twist_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
  wheel_separation: 0.4
  wheel_radius: 0.08
  cmd_vel_timeout: 0.25
  odom_frame_id: odom
  base_frame_id: base_footprint
  enable_odom_tf: true